### ISSUE TITLE
Error Code=4011

### ISSUE THREAD

**Issue by XTRMsavage** [Acly/krita-ai-diffusion#165]
When I try to use pose option this comes up. "Error: Error transferring http://127.0.0.1:81 88/prompt - server replied: nternal Server Eror (url=http://127.0.0.1:8188)
prompt, code=4011"

I am using this connection setting

<img width="628" alt="image" src="https://github.com/Acly/krita-ai-diffusion/assets/90519573/efca320f-be91-4032-8de7-21f9746d315b">

**Comment by tashachan28** [comment]
I'm dealing with the same error. 
![errorkiritaai](https://github.com/Acly/krita-ai-diffusion/assets/81396969/3e16b291-7423-4b14-8744-e5fb3cece715)

```
2023-12-01 23:21:45,053 ERROR Error: Error transferring http://127.0.0.1:8188/prompt - server replied: Internal Server Error
Traceback (most recent call last):
  File "C:\Users\tasha\AppData\Roaming\krita\pykrita\ai_diffusion\ui\model.py", line 22, in _report_errors
    return await coro
  File "C:\Users\tasha\AppData\Roaming\krita\pykrita\ai_diffusion\ui\model.py", line 332, in _generate_control_layer
    job.id = await client.enqueue(work)
  File "C:\Users\tasha\AppData\Roaming\krita\pykrita\ai_diffusion\client.py", line 207, in enqueue
    result = await self._post("prompt", data)
  File "C:\Users\tasha\AppData\Roaming\krita\pykrita\ai_diffusion\client.py", line 203, in _post
    return await self._requests.post(f"{self.url}/{op}", data)
ai_diffusion.network.NetworkError: Error transferring http://127.0.0.1:8188/prompt - server replied: Internal Server Error
```

**Comment by Acly** [comment]
@tashachan28 in your case it does not find the DWPreprocessor node. It's part of [comfyui_controlnet_aux](https://github.com/Fannovel16/comfyui_controlnet_aux) custom nodes - you probably have it installed, but maybe it's an old version?

**Comment by tashachan28** [comment]
I updated it and now everything but open pose works, 

```
2023-12-03 00:50:16,947 ERROR list indices must be integers or slices, not str
Traceback (most recent call last):
  File "C:\Users\tasha\AppData\Roaming\krita\pykrita\ai_diffusion\ui\model.py", line 575, in _handle_messages
    model.handle_message(msg)
  File "C:\Users\tasha\AppData\Roaming\krita\pykrita\ai_diffusion\ui\model.py", line 380, in handle_message
    job.control.image = self.add_control_layer(job, message.result)  # type: ignore
  File "C:\Users\tasha\AppData\Roaming\krita\pykrita\ai_diffusion\ui\model.py", line 426, in add_control_layer
    pose = Pose.from_open_pose_json(result)
  File "C:\Users\tasha\AppData\Roaming\krita\pykrita\ai_diffusion\pose.py", line 193, in from_open_pose_json
    extent = Extent(pose["canvas_width"], pose["canvas_height"])
TypeError: list indices must be integers or slices, not str
```

**Comment by Acly** [comment]
Ah, it turns out now the comfyui_controlnet_aux is _too new_, the pose json changed. I just updated mine to latest and get the same error. It's easy to fix, and release probably later today.

**Comment by Acly** [comment]
Pose issue is fixed in [1.9.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.9.0)

**Comment by Acly** [comment]
There is a large collection of SDXL ControlNet models here: https://huggingface.co/lllyasviel/sd_control_collection/tree/main

**Comment by XTRMsavage** [comment]
I am still getting the error, I cannot find this model (control-lora-openposexl2-rank) and now getting this error :(

<img width="512" alt="image" src="https://github.com/Acly/krita-ai-diffusion/assets/90519573/46d249d6-020b-4f87-9a45-678956924056">

<img width="1182" alt="image" src="https://github.com/Acly/krita-ai-diffusion/assets/90519573/b9a03001-bf09-46b4-8bcd-369482501842">

**Comment by Acly** [comment]
>  I cannot find this model (control-lora-openposexl2-rank)

It's just an alternative name, you only need one of them.

Error in first image looks like the one you'd get _before_ plugin 1.9.0 update. Check client.log to make sure.

Second error looks unrelated (some issue with ComfyUI Manager, but I think it can be ignored)

**Comment by EasyartDS** [comment]
Error: Error transferring http://127.0.0.1:8188/prompt - server replied: Internal ServerError [url=http://127.0.0.1:8188/prompt, code=401]     For days, I still couldn't solve the damn problem. God help me

**Comment by Acly** [comment]
Need to look at the server output to get the actual error. That will be on your console if you run Comfy manually or server.log if via the plugin.
