### ISSUE TITLE
Server execution error: CUDA error.

### ISSUE THREAD

**Issue by XILegacyy** [Acly/krita-ai-diffusion#1693]
i use nvidia 5070 TI and this error message already trying all the thing online but nothing works help please

Server execution error: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by XILegacyy** [comment]
its fine when im only using comfyui idk why

**Comment by arch0820** [comment]
저 역시 nvidia 5070으로 교체 후 같은 오류메시지가 나옵니다.
10일을 매달렸으나 실패했습니다. ㅠ
당분간 온라인 결제 서비스를 받아야 할까요?

nvidiad에서 해결해야 할 문제?
아니면 krita ai에서 해결해야 하는 문제일까요?
관계자님 도움을 주세요.

서버 실행 오류: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by XILegacyy** [comment]
i think the problem is the torch because torch is not updated to cuda 12.8?

**Comment by Acly** [comment]
You need to install ComfyUI with preview version of torch and cuda 12.8
https://blog.comfy.org/p/how-to-get-comfyui-running-on-your

#1586 #1620

**Comment by arch0820** [comment]
기다리던 답변 감사합니다. 다시 시도해보겠습니다.


2025년 4월 1일 (화) 오후 5:10, Acly ***@***.***>님이 작성:

**Comment by arch0820** [comment]
Resolved There is another error
Error: Could not find LoRA 'lcm' (lcm-lora-sdv1-5.safetensors, lcm/sd1.5/pytorch_lora_weights.safetensors) used by sampler preset 'Realtime - LCM' Please advise

**Comment by T-A-R** [comment]
Did this "You need to install ComfyUI with preview version of torch and cuda 12.8" but still not works.
Any solution now?
