### ISSUE TITLE
Upscale not working with regions

### ISSUE THREAD

**Issue by sdk401** [Acly/krita-ai-diffusion#791]
Getting "division by zero" error when trying to use upscale with region prompts.
Without regions, or with empty regional layers, upscale is working ok.

2024-06-12 10:44:01,070 ERROR Error: division by zero
Traceback (most recent call last):
  File "C:\Users\sardu\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 1032, in _report_errors
    return await coro
  File "C:\Users\sardu\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 204, in _enqueue_job
    job.id = await client.enqueue(input, self.queue_front)
  File "C:\Users\sardu\AppData\Roaming\krita\pykrita\ai_diffusion\comfy_client.py", line 155, in enqueue
    workflow = create_workflow(work, self.models)
  File "C:\Users\sardu\AppData\Roaming\krita\pykrita\ai_diffusion\workflow.py", line 1176, in create
    return upscale_tiled(
  File "C:\Users\sardu\AppData\Roaming\krita\pykrita\ai_diffusion\workflow.py", line 966, in upscale_tiled
    regions = [tiled_region(r, i, bounds) for r in tile_cond.regions]
  File "C:\Users\sardu\AppData\Roaming\krita\pykrita\ai_diffusion\workflow.py", line 966, in <listcomp>
    regions = [tiled_region(r, i, bounds) for r in tile_cond.regions]
  File "C:\Users\sardu\AppData\Roaming\krita\pykrita\ai_diffusion\workflow.py", line 950, in tiled_region
    coverage = Bounds.intersection(tile_bounds, region_bounds).area / tile_bounds.area
ZeroDivisionError: division by zero

**Comment by sdk401** [comment]
Tested a little more, some times upscaling works, sometimes not, but I'm getting this error every time on one particular file. Here is the link to the file:

https://drive.google.com/file/d/1VZdINHiP5VBvUWLJO6LTSeoSB2zhAA5v/view?usp=sharing

Can't see what's so special about it, it's a little larger than default sdxl res, maybe this is the reason?

**Comment by Acly** [comment]
Thanks for the file, I can reproduce it. It's likely triggered by specific resolutions.

**Comment by Acly** [comment]
Fixed in [1.18.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.18.1)

**Comment by iconberg** [comment]
I still have this bug if i upscale a picture for example with size of 297x170, but it seems the upscale is done but refine option not executed. I activated the logging docker with all options but there is no "division by zero" logged.
![krita_ai_div_by_zero_upscale_redefine](https://github.com/Acly/krita-ai-diffusion/assets/8441455/9975c213-cc44-47b1-bb56-879eadbdbd1b)

[KritaSystemInformation.txt](https://github.com/user-attachments/files/16089457/KritaSystemInformation.txt)
