### ISSUE TITLE
fbgemm.dll - The specified module could not be found

### ISSUE THREAD

**Issue by Hii-ops** [Acly/krita-ai-diffusion#965]
I have problem with launch local managed server on AI plugin.

INFO OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\opako\AppData\Roaming\krita\pykrita\ComfyUI\python\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
ERROR

Is there any solution?

Thanx

**Comment by hermessalomon** [comment]
I have the same issue

**Comment by hermessalomon** [comment]
I found the solution, you have 2 options, the most simple is to install this dll and adding it to your /windows/system32 folder. 

https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d/download

if it doesnt fix the error you will have to download the dependencies tool to find wich .dll is lost and just download it and it should be fixed.

**Comment by Hysocs** [comment]
sadly the dll is present and it just cant find it, no lost dlls found.

**Comment by Hii-ops** [comment]
Thanks bro manually adding dll fixed it. Its working now

**Comment by ChelOis** [comment]
Thank a lot. I solved the same problem here with your tip.

**Comment by bitjager** [comment]
> I found the solution, you have 2 options, the most simple is to install this dll and adding it to your /windows/system32 folder.
> 
> https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d/download
> 
> if it doesnt fix the error you will have to download the dependencies tool to find wich .dll is lost and just download it and it should be fixed.

thanx this works for me, windows 11
just drop .dll on /windows/system32 folder

**Comment by meikodunois** [comment]
Same issue, and I can't download that DLL, for some reason i can't access to DLLMe in my country, and i don't find it anywhere else

**Comment by ChelOis** [comment]
SetupVPN extension for your browser.

**Comment by Acly** [comment]
For the latest release [v1.21.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.21.0) I pinned the pytorch version 2.3.1
That means people who (re-)install with that version shouldn't run into this problem.

Maybe it will be fixed on pytorch side in the future by including the DLL, but I'm not sure and it'll probably take some time: https://github.com/pytorch/pytorch/issues/131662

**Comment by Evionail** [comment]
> Same issue, and I can't download that DLL, for some reason i can't access to DLLMe in my country, and i don't find it anywhere else

If Drive works on your country then here have the file I uploaded to Drive
https://drive.google.com/file/d/1R_ZQjL0r1eBzDZIuFUykDqy5P2L4-92W/view

**Comment by flaviohr** [comment]
I was solved that error by installing "Build Tools for Visual Studio 2022"
but you can try too "Build Tools for Visual Studio 2019"

**Comment by zenkovski** [comment]
> I found the solution, you have 2 options, the most simple is to install this dll and adding it to your /windows/system32 folder.
> 
> https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d/download
> 
> if it doesnt fix the error you will have to download the dependencies tool to find wich .dll is lost and just download it and it should be fixed.

thanks g its working now

**Comment by pistqak** [comment]
> I have problem with launch local managed server on AI plugin.
> 
> INFO OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\opako\AppData\Roaming\krita\pykrita\ComfyUI\python\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies. ERROR
> 
> Is there any solution?
> 
> Thanx

Mine still not working 
![image](https://github.com/user-attachments/assets/3884f752-dd7a-4a5e-9f69-dd0950d66e66)
![image](https://github.com/user-attachments/assets/b0e68f25-29e5-4805-aec4-e71a5e6046ac)

**Comment by hermessalomon** [comment]
@pistqak download the dependencies tool to find wich one is missing to you, if you already have the lobomp140 it should be a different dependencie and it will give you wich one is missing 

here is the link for the tool 

https://github.com/lucasg/Dependencies

**Comment by pistqak** [comment]
> @pistqak download the dependencies tool to find wich one is missing to you, if you already have the libomp140 it should be a different dependencie and it will give you wich one is missing 
> 
> 
> 
> here is the link for the tool 
> 
> 
> 
> https://github.com/lucasg/Dependencies

thx

**Comment by james2342342514** [comment]
## THIS WORKED FOR ME: 

### If you encounter an error related to missing DLL files (specifically fbgemm.dll) on Windows 11, follow these steps to resolve the issue:

- Download and run the Visual Studio Installer.
- Select "Modify" if you have Visual Studio installed, or proceed with a new installation.
- Go to the "Individual components" tab.
- Search for "C++ 2022" in the search box.
- Check the box next to "MSVC v143 - VS 2022 C++ x64/x86 build tools (Latest)".
- Click "Modify" or "Install" to proceed with the installation.
- Restart your computer after the installation is complete.
- This installs the necessary C++ build tools and runtime libraries that PyTorch depends on.

**Comment by ChelOis** [comment]
> ## THIS WORKED FOR ME:
> ### If you encounter an error related to missing DLL files (specifically fbgemm.dll) on Windows 11, follow these steps to resolve the issue:
> 
>     1. Download and run the Visual Studio Installer.
> 
>     2. Select "Modify" if you have Visual Studio installed, or proceed with a new installation.
> 
>     3. Go to the "Individual components" tab.
> 
>     4. Search for "C++ 2022" in the search box.
> 
>     5. Check the box next to "MSVC v143 - VS 2022 C++ x64/x86 build tools (Latest)".
> 
>     6. Click "Modify" or "Install" to proceed with the installation.
> 
>     7. Restart your computer after the installation is complete.
> 
>     8. This installs the necessary C++ build tools and runtime libraries that PyTorch depends on.

First, I solved the problem with the tip provided by hermessalomon, I mean, copying libomp140.x86_64.dll to Windows\System32 folder. I can confirm adding "MSVC v143 - VS 2022 C++ x64/x86 build tools (Latest)" to my installation of Visual Studio also injects that ddl. Thank to both of you

**Comment by npbenjohnson** [comment]
> ## THIS WORKED FOR ME:
> ### If you encounter an error related to missing DLL files (specifically fbgemm.dll) on Windows 11, follow these steps to resolve the issue:
> 1. Download and run the Visual Studio Installer.
> 2. Select "Modify" if you have Visual Studio installed, or proceed with a new installation.
> 3. Go to the "Individual components" tab.
> 4. Search for "C++ 2022" in the search box.
> 5. Check the box next to "MSVC v143 - VS 2022 C++ x64/x86 build tools (Latest)".
> 6. Click "Modify" or "Install" to proceed with the installation.
> 7. Restart your computer after the installation is complete.
> 8. This installs the necessary C++ build tools and runtime libraries that PyTorch depends on.
Thanks for the fix!
Short version:
```
winget install --id Microsoft.VisualStudio.2022.BuildTools --override "--passive --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
```

**Comment by AgMagGag** [comment]
> > ## THIS WORKED FOR ME:
> > ### If you encounter an error related to missing DLL files (specifically fbgemm.dll) on Windows 11, follow these steps to resolve the issue:
> > 
> > 1. Download and run the Visual Studio Installer.
> > 2. Select "Modify" if you have Visual Studio installed, or proceed with a new installation.
> > 3. Go to the "Individual components" tab.
> > 4. Search for "C++ 2022" in the search box.
> > 5. Check the box next to "MSVC v143 - VS 2022 C++ x64/x86 build tools (Latest)".
> > 6. Click "Modify" or "Install" to proceed with the installation.
> > 7. Restart your computer after the installation is complete.
> > 8. This installs the necessary C++ build tools and runtime libraries that PyTorch depends on.
> 
> Thanks for the fix! Short version:
> 
> ```
> winget install --id Microsoft.VisualStudio.2022.BuildTools --override "--passive --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
> ```

Thank you so freaking much for not making me use some random dll because i'm pretty sure that's how ya hack ya self. Xo

**Comment by ChelOis** [comment]
> Thank you so freaking much for not making me use some random dll because i'm pretty sure that's how ya hack ya self. Xo

The DLL suggested by hermessalomon is digitally signed by Autodesk, so, no risk.

**Comment by AadhithSridharan** [comment]
> I found the solution, you have 2 options, the most simple is to install this dll and adding it to your /windows/system32 folder.
> https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d/download
> if it doesnt fix the error you will have to download the dependencies tool to find wich .dll is lost and just download it and it should be fixed.

Tqsm @hermessalomon this works

**Comment by berwinsingh** [comment]
> I found the solution, you have 2 options, the most simple is to install this dll and adding it to your /windows/system32 folder.
> 
> https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d/download
> 
> if it doesnt fix the error you will have to download the dependencies tool to find wich .dll is lost and just download it and it should be fixed.

This was a life saver. I was looking for a solution for such a long time, but this worked like a charm

**Comment by AARADHYAPATEL** [comment]
Hey there,
I have the fbgemm.dll but it seems corrupted, should I delete it and then reinstall it

**Comment by AARADHYAPATEL** [comment]
As it is still giving the issue that fbgemm.dll or one of its dependencies are corrupted

**Comment by Timmate** [comment]
> For the latest release [v1.21.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.21.0) I pinned the pytorch version to 2.3.1 That means people who (re-)install with that version shouldn't run into this problem.
> 
> Maybe it will be fixed on pytorch side in the future by including the DLL, but I'm not sure and it'll probably take some time: [pytorch/pytorch#131662](https://github.com/pytorch/pytorch/issues/131662)

This one solved it for me, didn't even need to fiddle with the C++ stuff. Much appreciated!

**Comment by AARADHYAPATEL** [comment]
I do not have space in my computer for zenkovski's option and I already have fbgemm.dll, so neither option works

**Comment by ahmadatarvo** [comment]
> I found the solution, you have 2 options, the most simple is to install this dll and adding it to your /windows/system32 folder.
> 
> https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d/download
> 
> if it doesnt fix the error you will have to download the dependencies tool to find wich .dll is lost and just download it and it should be fixed.

Solved my issue my adding .dll file in windows/system32
Thanks a lot

**Comment by Kaizer1er** [comment]
> J'ai trouvé la solution, vous avez 2 options, la plus simple est d'installer cette dll et de l'ajouter à votre dossier /windows/system32.
> 
> https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d/download
> 
> si cela ne corrige pas l'erreur, vous devrez télécharger l'outil de dépendances pour trouver quel .dll est perdu et le télécharger simplement et il devrait être corrigé.

Merci mec pour le tifs

**Comment by Aron-Arboleda** [comment]
> I found the solution, you have 2 options, the most simple is to install this dll and adding it to your /windows/system32 folder.
> 
> https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d/download
> 
> if it doesnt fix the error you will have to download the dependencies tool to find wich .dll is lost and just download it and it should be fixed.

THANKS SO MUCHH!

**Comment by NgoDuc2505** [comment]
> /windows/system32

Thanks a lot. It works...

**Comment by MusabAlam** [comment]
> I found the solution, you have 2 options, the most simple is to install this dll and adding it to your /windows/system32 folder.
> 
> https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d/download
> 
> if it doesnt fix the error you will have to download the dependencies tool to find wich .dll is lost and just download it and it should be fixed.

It's helping

**Comment by Zavieer** [comment]
> I found the solution, you have 2 options, the most simple is to install this dll and adding it to your /windows/system32 folder.
> 
> https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d/download
> 
> if it doesnt fix the error you will have to download the dependencies tool to find wich .dll is lost and just download it and it should be fixed.

Thank you very much, it solved my problem.

**Comment by pollo-coder** [comment]
A thing is not clear to me. Is (or at least was) this a _bug_ in pytorch, which will be fixed (or maybe already fixed in 2.4.1)?

**Comment by Acly** [comment]
Yes it was a bug in pytorch. They fixed it fairly quickly, so I expect it's no longer be a problem in 2.4.1
